command_timeout = 1200

[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = 'bold blue'
symbol = '󰸏 '

[aws.region_aliases]
ap-northeast-1 = 'tokyo'
us-east-1 = 'virginia'

[aws.profile_aliases]
CompanyGroupFrobozzOnCallAccess = 'Frobozz'

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " 󰌾"

[docker_context]
symbol = " "
disabled = true

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[gcloud]
symbol = "󱇶 "
format = 'on [$symbol$account(@$domain)(\($project\))]($style) '

[git_branch]
# symbol = " "
symbol = "󰊢 "

[git_metrics]
added_style = 'bold blue'
format = '[ $added]($added_style)/[ $deleted]($deleted_style) '
disabled = false

[git_status]
conflicted = "="
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕ ⇡${ahead_count}⇣${behind_count}'
up_to_date = '[󰸞](green)'
untracked = "?"
stashed = '$'
modified = "!"
staged = '[++\($count\)](green)'
renamed = "»"
deleted = "✘ "
style = "bold red"
format = '([\[$all_status$ahead_behind\]]($style) )'
disabled = false

[golang]
# symbol = " "
symbol = "󰟓 "
format = "[$symbol($version )]($style)"

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[swift]
symbol = " "

[terraform]
symbol = "󱁢 "
format = "[$symbol]($style)"

[zig]
symbol = " "
